title: Hachy
description: > # this means to ignore newlines until "baseurl:"
  hachy's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hachy.github.io" # the base hostname & protocol for your site
twitter_username: hachy01
github_username:  hachy

# Build settings
markdown: redcarpet
redcarpet:
  extensions: []
kramdown:
  input: GFM
